apiVersion: apps/v1
kind: Deployment

metadata:
  name: react-tetris-deployment

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: react-tetris

  template:
    metadata:
      labels:
        app: react-tetris

    spec:
      containers:
      - name: react-tetris

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 80